target 'FMAssetStream', :exclusive => true do
  pod "FMAssetStream", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FMAssetStream", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'EXPMatchers+FBSnapshotTest'
end
